### PR TITLE
Apple Vision Pro Clone

### PR DESCRIPTION
**Pull request by Sanchita1304**
Added The Apple Vision Pro Clone in project section.
It have the main page which shows the visual effects by scrolling down.
It is done by using HTML, CSS, JavaScript.

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
@Sanchita1304 Great. But you have to add the project in the projects.json too.
Other wise it will not show on the UI.

**Comment by SyedImtiyaz-1** [comment]
image

@Sanchita1304  Add like this.
### - If you have any query then feel free to msg me on [LinkedIn](https://linkedin.com/in/imtiyaz-sde)

**Comment by Sanchita1304** [comment]
Do I have to add all images of "Apple vision canvas images" in the backend folder? and in the project.json do I have to add all "Apple vision canvas images" folder images as the slider image?

Its showing premium for messaging you in linkedin.

**Comment by SyedImtiyaz-1** [comment]
> Do I have to add all images of "Apple vision canvas images" in the backend folder? and in the project.json do I have to add all "Apple vision canvas images" folder images as the slider image?
> 
> Its showing premium for messaging you in linkedin.

Yes you have to add name of the proejct and have to add the imgs.

**Comment by Sanchita1304** [comment]
image

 
I have added this, is it ok?

**Comment by SyedImtiyaz-1** [comment]
Yes. It's fine !!!

**Pull request merged**
