### PR TITLE
Uiupdate

### PR DESCRIPTION
**Pull request by vatsalshah041**
Uiupdate
Task done:
1)Submit Buton alignment in responsive view as well
2)Adding error on the form instead of using alerts of js
3)aligned the map image properly

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
PR willl get merge on 1 OCt

**Comment by vatsalshah041** [comment]
> PR willl get merge on 1 Oct

ok thank you 👍 :)

**Comment by vatsalshah041** [comment]
> PR willl get merge on 1 Oct

can you the pr as hacktoberfest has started

**Comment by SyedImtiyaz-1** [comment]
There are conflicts.
image

**Pull request closed without merging**
